/* manual insertions created by team Six 
for database with name *_small */
insert into GPU values('123ABC', 'PNY', 'RTX2080TI', 11)
insert into GPU values('123ABD', 'PNY', 'RTX2080TI', 11)
insert into GPU values('123ABE', 'PNY', 'RTX2080TI', 11)
insert into GPU values(NULL, 'MSI' 'GTX1080Ti', 11)
insert into GPU values(NULL, 'MSI' 'GTX1080Ti', 11)
insert into GPU values('124ABC', 'MSI' 'GTX1080Ti', 11)
insert into GPU values('128ABC', 'MSI' 'GTX1080Ti', 11)
insert into GPU values('921ABD', 'TITAN', 'RTX', 24)
insert into GPU values(NULL, 'TITAN', 'RTX', 24)
insert into GPU values('802ASD', 'TITAN', 'RTX', 24)

insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)
insert into Memory values (NULL, 64, 'DDR4', 2933, 'DIMM')
insert into Memory values (NULL, NULL, NULL, NULL, NULL)

insert into CPU values (NULL, 36, 18)
insert into CPU values (NULL, 36, 18)
insert into CPU values (NULL, 36, 18)
insert into CPU values (NULL, 36, 18)

insert into PSU values (NULL, 1600)
insert into PSU values (NULL, 1600)
insert into PSU values (NULL, NULL)
insert into PSU values (NULL, NULL)

insert into Drives values(NULL, 128, 'SSD', 'IDK')
insert into Drives values(NULL, 3000, 'HDD', 'IDK')
insert into Drives values(NULL, 3000, 'HDD', 'IDK')
insert into Drives values(NULL, 1000, 'SSD', 'IDK')
insert into Drives values(NULL, 1000, 'SSD', 'IDK')
insert into Drives values(NULL, 1000, 'SSD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')
insert into Drives values(NULL, 8000, 'HDD', 'IDK')

insert into Display values(NULL, 24, '1920X1080')
insert into Display values(NULL, 27, '1920X1080')
insert into Display values(NULL, 24, '1920X1080')

insert into Computer values(NULL, )
insert into Computer values(NULL, )
insert into Computer values(NULL, )
insert into Computer values(NULL, )